# Generated by Django 3.1.3 on 2020-11-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('callePrincipal', models.CharField(max_length=60)),
                ('calleSecundaria', models.CharField(max_length=60)),
                ('referencia', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('idEmail', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('idEstadoCivil', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('estadoCivil', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.ciudad')),
                ('Direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.direccion')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.email')),
                ('Estado_Civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.estado-civil')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('idSexo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('idTelefono', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=30)),
                ('claveUsuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaTelefono',
            fields=[
                ('idPersonaCelular', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.persona')),
                ('Telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.telefono')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='Sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.sexo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='Tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.tipo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.usuario'),
        ),
    ]
