# Generated by Django 3.1.3 on 2020-11-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ciudad',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='callePrincipal',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calleSecundaria',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='referencia',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='email',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidoMaterno',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidoPaterno',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='sexo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=1000),
        ),
    ]
