# Generated by Django 3.1.3 on 2020-11-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20201117_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ciudad',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='sexo',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombreUsuario',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
